#ifndef CONSTANT_H
#define CONSTANT_H

#define CONTROL_MODE_POSITION		1
#define CONTROL_MODE_VELOCITY		2
#define CONTROL_MODE_TORQUE		3

#define CAPTURE_ACTUAL_POSITION		6
#define CAPTURE_RAW_POSITION		25

#define POSITION_DEFAULT		0
#define TARGET_DEFAULT			0
#define TARGET_MIN			-24*CNT_PER_REV*REV_PER_INCH
#define TARGET_MAX			0//24*CNT_PER_REV*REV_PER_INCH//2147483647
#define FEEDRATE_DEFAULT		1
#define FEEDRATE_MAX			1000//1366
#define FEEDRATE_MIN			1
#define FEEDRATE_OVERRIDE_DEFAULT	100
#define FEEDRATE_OVERRIDE_MAX		120
#define FEEDRATE_OVERRIDE_MIN		10
#define FEEDRATE_OVERRIDE_INC		5
#define SPINDLE_DEFAULT			100
#define SPINDLE_MAX			1000
#define SPINDLE_MIN			100
#define SPINDLE_OVERRIDE_DEFAULT	100
#define SPINDLE_OVERRIDE_MAX		120
#define SPINDLE_OVERRIDE_MIN		50
#define SPINDLE_OVERRIDE_INC		5
#define STATUS_LENGTH			100

#define CNT_PER_REV			4096.0
#define REV_PER_INCH			9.0
#define INCH_PER_REV			1.0/REV_PER_INCH
#define VEL_PER_RPM			1366.0/1000.5

#define FEEDRATE_RAPID			1000

#define STATE_STARTUP		0
#define STATE_STARTUP2		1
#define STATE_IDLE		2
#define STATE_START		3
#define STATE_START2		4
#define STATE_FEED		5
#define STATE_RETURN		6
#define STATE_RETURN_ZERO	7
#define STATE_STOP		8
#define STATE_WAIT_COMPLETE	9
#define STATE_EMERGENCY_RETURN_START	10
#define STATE_OVERFLOW		11
#define STATE_ERROR		12

#define SIMPLE_STATUS_MOVING	0
#define SIMPLE_STATUS_ERROR	1
#define SIMPLE_STATUS_IDLE	2

#define TIME_UPDATE_DISPLAY	150
#define TIME_UPDATE_POSITIONS	20
#define TIME_UPDATE_STATE	250

#define INPUT_TYPE_NONE		0
#define INPUT_TYPE_TARGET	1
#define INPUT_TYPE_FEEDRATE	2
#define INPUT_TYPE_SPINDLE	3

#define BACKLASH_MOVE_AMOUNT	0.125*CNT_PER_REV*REV_PER_INCH
#define ZERO_OFFSET_TOLERANCE	2

#define JOG_MODE_DEFAULT	-1
#define JOG_MODE_NONE		-1
#define JOG_MODE_1X		0
#define JOG_MODE_10X		1
#define JOG_MODE_100X		2
#define JOG_MODE_001		3
#define JOG_MODE_01		4
#define JOG_MODE_1		5

//Jog Feedrates/16384 = x/Set max feedrate
//Used as ABSPOS in Velocity Mode
#define JOG_FEEDRATE_1X		163
#define JOG_FEEDRATE_10X	1638
#define JOG_FEEDRATE_100X	16384
#define JOG_FEEDAMOUNT_001	0.001*CNT_PER_REV*REV_PER_INCH
#define JOG_FEEDAMOUNT_01	0.01*CNT_PER_REV*REV_PER_INCH
#define JOG_FEEDAMOUNT_1	0.1*CNT_PER_REV*REV_PER_INCH
#define JOG_POS_TARGET		100000000
#define JOG_NEG_TARGET		-100000000

#define JOG_STOP		0
#define JOG_FORWARD		1
#define JOG_REVERSE		-1

//#define STOP_DECEL_RATE		136 //Per cycle of STATE_STOP itteration
//#define STOP_TOL		10

#define INPUT_RAPID_RETRACT	0
#define INPUT_AUTO_MODE		1
#define INPUT_OVERFLOW		2
#define INPUT_AUTOMAN		3
#define INPUT_LIMIT_POS		4
#define INPUT_LIMIT_NEG		5


#define OUTPUT_DRIVE_ON		0
#define OUTPUT_CYCLE_START	2
#define OUTPUT_FEED_FORWARD	3
#define OUTPUT_RAPID_RETRACT	4

#define DEBOUNCE_LOOPS		5

#endif //CONSTANT_H
